# Generated by Django 3.2.10 on 2022-02-10 20:31

from django.db import migrations, models
import xxlimited


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0018_postfavoritos_delete_favoritos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(default=xxlimited.Null, max_length=100),
        ),
    ]
